name: bmad-personal-assistant
description: "A personal assistant expansion pack for professionals, focusing on efficient learning, professional research, data organization, IT assistance, document/report generation, and life management."
version: 0.1.0
